version: '3.8'

services:
  # 1. База данных
  database:
    container_name: ak_dv_database
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: avtokraski_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. Бэкенд
  backend:
    container_name: ak_dv_backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: avtokraski_db

  # 3. Фронтенд (ИСПРАВЛЕНО)
  frontend:
    container_name: ak_dv_frontend
    # Используем готовый образ, чтобы не искать Dockerfile
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      # 1. Показываем сайт прямо из твоей папки (Live-режим!)
      - ./frontend:/usr/share/nginx/html
      # 2. Подключаем настройки защиты
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # 3. Подключаем файл с паролем
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - backend
      - database

volumes:
  pgdata: